### ISSUE TITLE
non webkit support?

### ISSUE THREAD

**Issue by fionnbharra** [adamschwartz/magic-of-css#4]
The transitions in http://adamschwartz.co/magic-of-css/chapters/6-transitions/ seem to be web kit only. 

Do you have plans to add ff support?

**Comment by adamschwartz** [comment]
The first example doesn't use any `-webkit` prefixes yet it doesn't work due to [this strange bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=990340):

```
<style>
    div {
        overflow: auto
    }

    div:before {
        content: ":before"
    }

    span {
        opacity: 0;
        transition: opacity 1200ms
    }

    div:hover span {
        opacity: 1
    }
</style>

<div>
    <span>My opacity doesn't transition as it should :(</span>
</div>
```

See [jsFiddle](http://jsfiddle.net/adamschwartz/h8Nk7/show/light). (Tested in FF 27.0.1 and 28.0 on Mac OS X.)

For now, I was able to find [a workaround](https://github.com/adamschwartz/magic-of-css/commit/348837cb99198211c4012e5298cc307f5c3de300#diff-1a19225d29225ea54a929fc96fd7ae82R80) by setting `overflow: hidden` on `.typography-example`.

**Comment by fionnbharra** [comment]
Looks great, good stuff.
